### ISSUE TITLE
reading from bitcoind raw files crashes with NegativeArraySizeException.

### ISSUE THREAD

**Issue by stefanwouldgo** [bitcoinj/bitcoinj#1554] opened 2018-04-12 07:45 UTC
bge_1       | Caused by: java.lang.NegativeArraySizeException
bge_1       |   at org.bitcoinj.core.Message.readBytes(Message.java:334)
bge_1       |   at org.bitcoinj.core.TransactionInput.parse(TransactionInput.java:143)
bge_1       |   at org.bitcoinj.core.Message.<init>(Message.java:96)
bge_1       |   at org.bitcoinj.core.Message.<init>(Message.java:128)
bge_1       |   at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:57)
bge_1       |   at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:133)
bge_1       |   at org.bitcoinj.core.Transaction.parse(Transaction.java:569)
bge_1       |   at org.bitcoinj.core.Message.<init>(Message.java:96)
bge_1       |   at org.bitcoinj.core.Message.<init>(Message.java:128)
bge_1       |   at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:57)
bge_1       |   at org.bitcoinj.core.Transaction.<init>(Transaction.java:237)
bge_1       |   at org.bitcoinj.core.Block.parseTransactions(Block.java:242)
bge_1       |   at org.bitcoinj.core.Block.parse(Block.java:266)
bge_1       |   at org.bitcoinj.core.Message.<init>(Message.java:96)
bge_1       |   at org.bitcoinj.core.Message.<init>(Message.java:128)
bge_1       |   at org.bitcoinj.core.Block.<init>(Block.java:162)
bge_1       |   at org.bitcoinj.core.BitcoinSerializer.makeBlock(BitcoinSerializer.java:270)
bge_1       |   at org.bitcoinj.core.MessageSerializer.makeBlock(MessageSerializer.java:72)
bge_1       |   at org.bitcoinj.utils.BlockFileLoader.loadNextBlock(BlockFileLoader.java:154)
bge_1       |   at org.bitcoinj.utils.BlockFileLoader.hasNext(BlockFileLoader.java:87)
bge_1       |   at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:39)

This is bitcoinj 0.14.7, about block 4818xx.

**Comment by schildbach** [comment] 2018-04-12 10:35
Duplicate of #1385.

**Closed by schildbach** 2018-04-12 10:35 UTC
