### ISSUE TITLE
org.bitcoinj.crypto.BIP38PrivateKeyTest tests fail on MacOS/Java 8u152

### ISSUE THREAD

**Issue by bendyarm** [bitcoinj/bitcoinj#1481] opened 2017-11-10 00:47 UTC
I followed the instructions for a full build but I got test failures.
MacOS 10.13.1
Java version: Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Apache Maven 3.5.2
git clone https://github.com/bitcoinj/bitcoinj/
mvn clean package

Up-to-date with master:
```
$ git log | head -n 1
commit 3cc652858c75227edae620e7471481264f560198
```

Here's an example failure:
```
bip38testvector_noCompression_noEcMultiply_test1(org.bitcoinj.crypto.BIP38PrivateKeyTest)  Time elapsed: 0.258 sec  <<< ERROR!
java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size or default parameters
	at org.bitcoinj.crypto.BIP38PrivateKeyTest.bip38testvector_noCompression_noEcMultiply_test1(BIP38PrivateKeyTest.java:42)
Caused by: java.security.InvalidKeyException: Illegal key size or default parameters
	at org.bitcoinj.crypto.BIP38PrivateKeyTest.bip38testvector_noCompression_noEcMultiply_test1(BIP38PrivateKeyTest.java:42)

```
Summary of tests that failed:
```
Tests in error: 
  BIP38PrivateKeyTest.badPassphrase »  Unexpected exception, expected<org.bitcoi...
  BIP38PrivateKeyTest.bip38testvector_compression_noEcMultiply_test1:75 » Runtime
  BIP38PrivateKeyTest.bip38testvector_compression_noEcMultiply_test2:84 » Runtime
  BIP38PrivateKeyTest.bip38testvector_ecMultiply_noCompression_lotAndSequence_test1:111 » Runtime
  BIP38PrivateKeyTest.bip38testvector_ecMultiply_noCompression_lotAndSequence_test2:120 » Runtime
  BIP38PrivateKeyTest.bip38testvector_ecMultiply_noCompression_noLotAndSequence_test1:93 » Runtime
  BIP38PrivateKeyTest.bip38testvector_ecMultiply_noCompression_noLotAndSequence_test2:102 » Runtime
  BIP38PrivateKeyTest.bip38testvector_noCompression_noEcMultiply_test1:42 » Runtime
  BIP38PrivateKeyTest.bip38testvector_noCompression_noEcMultiply_test2:51 » Runtime
  BIP38PrivateKeyTest.bip38testvector_noCompression_noEcMultiply_test3:66 » Runtime
  BIP38PrivateKeyTest.bitaddress_testnet:140 » Runtime java.security.InvalidKeyE...
  BIP38PrivateKeyTest.bitcoinpaperwallet_testnet:130 » Runtime java.security.Inv...

Tests run: 5262, Failures: 0, Errors: 12, Skipped: 4
```

**Comment by schildbach** [comment] 2017-11-10 09:37
Can you try if the current release-0.14 branch builds? If yes, can try and bisect the commit on master that causes the failure?

**Comment by bendyarm** [comment] 2017-11-10 23:34
Same error in release-0.14.

**Comment by schildbach** [comment] 2017-11-18 15:10
This seems to be some MacOS specific problem. I'm not sure if we still have developers that use a Mac since Mike has left, so it will probably be hard to reproduce this issue.

**Comment by schildbach** [comment] 2017-11-18 15:20
If we implement the above suggestion, it should probably go into the `DRMWorkaround` class.

**Comment by tofutim** [comment] 2018-03-25 22:17
just wanted to report on a clean build on OSX I just ran into the same issue
```
[ERROR] Errors: 
[ERROR]   BIP38PrivateKeyTest.badPassphrase »  Unexpected exception, expected<org.bitcoi...
[ERROR]   BIP38PrivateKeyTest.bip38testvector_compression_noEcMultiply_test1:77 » Runtime
[ERROR]   BIP38PrivateKeyTest.bip38testvector_compression_noEcMultiply_test2:86 » Runtime
[ERROR]   BIP38PrivateKeyTest.bip38testvector_ecMultiply_noCompression_lotAndSequence_test1:113 » Runtime
[ERROR]   BIP38PrivateKeyTest.bip38testvector_ecMultiply_noCompression_lotAndSequence_test2:122 » Runtime
[ERROR]   BIP38PrivateKeyTest.bip38testvector_ecMultiply_noCompression_noLotAndSequence_test1:95 » Runtime
[ERROR]   BIP38PrivateKeyTest.bip38testvector_ecMultiply_noCompression_noLotAndSequence_test2:104 » Runtime
[ERROR]   BIP38PrivateKeyTest.bip38testvector_noCompression_noEcMultiply_test1:44 » Runtime
[ERROR]   BIP38PrivateKeyTest.bip38testvector_noCompression_noEcMultiply_test2:53 » Runtime
[ERROR]   BIP38PrivateKeyTest.bip38testvector_noCompression_noEcMultiply_test3:68 » Runtime
[ERROR]   BIP38PrivateKeyTest.bitaddress_testnet:142 » Runtime java.security.InvalidKeyE...
[ERROR]   BIP38PrivateKeyTest.bitcoinpaperwallet_testnet:132 » Runtime java.security.Inv...
```
I'll go switch #crypto.policy=unlimited. - but I wonder what this means for apps using this library. Does that mean that international use is prohibited if developed in the states?

**Comment by tofutim** [comment] 2018-03-25 22:19
In https://golb.hplar.ch/2017/10/JCE-policy-changes-in-Java-SE-8u151-and-8u152.html it is suggested that Java 9 (and I presume Java 10) have unlimited set by default now.

**Comment by Helios-vmg** [comment] 2018-04-26 15:04
I'm encountering this same error on Windows. JDK version is 1.8.0_131.

**Comment by systemsplanet** [comment] 2018-11-02 00:49
original JDK issue raised here https://bugs.openjdk.java.net/browse/JDK-7024850
and fixed in Java 9 here https://bugs.openjdk.java.net/browse/JDK-8170157

**Comment by systemsplanet** [comment] 2018-11-02 01:04
> I'm encountering this same error on Windows. JDK version is 1.8.0_131.

You will need local Windows admin rights to fix.
Any of these options should fix:
- roll back to an older JVM 1.8 
- install [JCE](https://www.oracle.com/technetwork/java/javase/downloads/jce-all-download-5170447.html)
- install JVM 1.8.0_151, as described here
[relnotes](https://www.oracle.com/technetwork/java/javase/8u151-relnotes-3850493.html)
 edit and uncomment
   C:\Program Files\Java\jdk1.8.0_152\jre\lib\security\java.security
         #crypto.policy=unlimited
- install JVM 1.9 b148+

Your best option is probably to add a method to DRMWorkaround.java to test if the exception was thrown, and use that to disable the failing tests. That will allow the tests to be run on boxes that support it and allow you to move past this until you can get an Admin to fix

**Comment by msgilligan** [comment] 2020-04-24 20:04
@schildbach I think we can close this issue.

**Closed** 2020-04-24 22:04 UTC
