### ISSUE TITLE
Error while syncing

### ISSUE THREAD

**Issue by globaltoken** [bitcoinj/bitcoinj#1429] opened 2017-08-03 22:12 UTC
While Syncing I receive this Error.
I added now sendheaders to my Code, but still receiving this Issue.

> 22:07:35 [NioClientManager] Peer Received unhandled message: org.bitcoinj.core.SendHeadersMessage@32306f39
22:07:35 [NioClientManager] BitcoinSerializer - No support for deserializing message with name sendcmpct
22:07:35 [NioClientManager] PeerSocketHandler - 
org.bitcoinj.core.ProtocolException: Error deserializing message 000200000000000000

	at org.bitcoinj.core.BitcoinSerializer.deserializePayload(BitcoinSerializer.java:186) ~[na:0.0]
	at org.bitcoinj.core.BitcoinSerializer.deserialize(BitcoinSerializer.java:147) ~[na:0.0]
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:153) ~[na:0.0]
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223) ~[na:0.0]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) ~[na:0.0]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) ~[na:0.0]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66) ~[na:0.0]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) ~[na:0.0]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
Caused by: java.lang.IllegalStateException: Length field has not been set in constructor for UnknownMessage after parse.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:530) ~[na:0.0]
	at org.bitcoinj.core.Message.<init>(Message.java:100) ~[na:0.0]
	at org.bitcoinj.core.Message.<init>(Message.java:124) ~[na:0.0]
	at org.bitcoinj.core.EmptyMessage.<init>(EmptyMessage.java:41) ~[na:0.0]
	at org.bitcoinj.core.UnknownMessage.<init>(UnknownMessage.java:28) ~[na:0.0]
	at org.bitcoinj.core.BitcoinSerializer.makeMessage(BitcoinSerializer.java:237) ~[na:0.0]
	at org.bitcoinj.core.BitcoinSerializer.deserializePayload(BitcoinSerializer.java:184) ~[na:0.0]
	... 9 common frames omitted
22:07:35 [NioClientManager] WalletApplication - bitcoinj uncaught exception
org.bitcoinj.core.ProtocolException: Error deserializing message 000200000000000000

**Comment by schildbach** [comment] 2017-08-11 17:07
This is weird, `sendcmpct` is protocol version 70014.

**Comment by schildbach** [comment] 2017-08-14 14:04
@globaltoken Can you double check what protocol version you're using?

**Comment by globaltoken** [comment] 2017-08-21 09:35
@schildbach I am Using latest Bitcoin Core Version as Syncing Node. This should be 70015 as Protocol Version. And I used here the Main Branch for testing.

Cheers

**Comment by schildbach** [comment] 2017-08-21 09:59
The main branch (master) currently uses 70012, and had been using 70001 when you opened this issue. Can you attach a more thorough logfile?

**Comment by globaltoken** [comment] 2017-08-21 10:02
I fixxed it because I added sendcmpct, feefilter and sendheaders as unhandled message. Then it began syncing. But thats not the smooth way.

**Comment by schildbach** [comment] 2017-09-28 14:33
I was not able to reproduce this on master and you said you fixed it for yourself, so I'm closing this for now.

**Closed by schildbach** 2017-09-28 14:33 UTC
