### ISSUE TITLE
NegativeArraySizeException

### ISSUE THREAD

**Issue by mfarnoosh** [bitcoinj/bitcoinj#1385] opened 2017-06-17 08:39 UTC
I want to use BlockFileLoader to parse bitcoin Testnet 3 blocks. but i get following error in some blocks.

Exception in thread "main" java.lang.NegativeArraySizeException
	at org.bitcoinj.core.Message.readBytes(Message.java:334)
	at org.bitcoinj.core.TransactionInput.parse(TransactionInput.java:138)
	at org.bitcoinj.core.Message.<init>(Message.java:96)
	at org.bitcoinj.core.Message.<init>(Message.java:128)
	at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:57)
	at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:128)
	at org.bitcoinj.core.Transaction.parse(Transaction.java:557)
	at org.bitcoinj.core.Message.<init>(Message.java:96)
	at org.bitcoinj.core.Message.<init>(Message.java:128)
	at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:57)
	at org.bitcoinj.core.Transaction.<init>(Transaction.java:227)
	at org.bitcoinj.core.Block.parseTransactions(Block.java:242)
	at org.bitcoinj.core.Block.parse(Block.java:266)
	at org.bitcoinj.core.Message.<init>(Message.java:96)
	at org.bitcoinj.core.Message.<init>(Message.java:128)
	at org.bitcoinj.core.Block.<init>(Block.java:162)
	at org.bitcoinj.core.BitcoinSerializer.makeBlock(BitcoinSerializer.java:270)
	at org.bitcoinj.core.MessageSerializer.makeBlock(MessageSerializer.java:72)
	at org.bitcoinj.utils.BlockFileLoader.loadNextBlock(BlockFileLoader.java:154)
	at org.bitcoinj.utils.BlockFileLoader.hasNext(BlockFileLoader.java:87)
	at com.areatak.Main.readByBitcoinJ(Main.java:38)

you can reproduce the problem with block with hash = 000000000000082544bacbd3ecc5f11565bea49842eabdda56a2ff2b1d1d6e17
this is  68240nd block in blk00047.dat

**Comment by schildbach** [comment] 2017-07-21 09:13
What version of bitcoinj is this on? Can you try on current master?

**Comment by mfarnoosh** [comment] 2017-08-06 11:05
I used v0.14.4.
I would try new version and tell you the result.

**Comment by eztam-** [comment] 2017-12-03 16:16
I have exactly the same problem with the lastest version 0.14.5

**Comment by owenson** [comment] 2017-12-24 17:04
I get the same error too, here's the stack trace:

Exception in thread "main" java.lang.NegativeArraySizeException
	at org.bitcoinj.core.Message.readBytes(Message.java:334)
	at org.bitcoinj.core.TransactionInput.parse(TransactionInput.java:138)
	at org.bitcoinj.core.Message.<init>(Message.java:96)
	at org.bitcoinj.core.Message.<init>(Message.java:128)
	at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:57)
	at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:128)
	at org.bitcoinj.core.Transaction.parse(Transaction.java:564)
	at org.bitcoinj.core.Message.<init>(Message.java:96)
	at org.bitcoinj.core.Message.<init>(Message.java:128)
	at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:57)
	at org.bitcoinj.core.Transaction.<init>(Transaction.java:232)
	at org.bitcoinj.core.Block.parseTransactions(Block.java:242)
	at org.bitcoinj.core.Block.parse(Block.java:266)
	at org.bitcoinj.core.Message.<init>(Message.java:96)
	at org.bitcoinj.core.Message.<init>(Message.java:128)
	at org.bitcoinj.core.Block.<init>(Block.java:162)
	at org.bitcoinj.core.BitcoinSerializer.makeBlock(BitcoinSerializer.java:270)
	at org.bitcoinj.core.MessageSerializer.makeBlock(MessageSerializer.java:72)
	at org.bitcoinj.utils.BlockFileLoader.loadNextBlock(BlockFileLoader.java:154)
	at org.bitcoinj.utils.BlockFileLoader.hasNext(BlockFileLoader.java:87)
	at com.gho.bitcoin.ChainOrder.main(ChainOrder.java:33)

**Comment by foror** [comment] 2017-12-28 16:56
Caused by https://github.com/bitcoin/bips/blob/master/bip-0144.mediawiki More details at https://github.com/ZuInnoTe/spark-hadoopcryptoledger-ds/issues/4

**Comment by mlerner** [comment] 2018-01-07 04:36
I'm running into this too. Is anyone working on this? If not, I could take a crack at it.

**Comment by mlerner** [comment] 2018-01-07 04:36
Is anyone working on this? If not, I could try to fix the issue.

**Comment by foror** [comment] 2018-01-07 05:37
https://github.com/bitcoinj/bitcoinj/tree/segwit

**Comment by artem7902** [comment] 2018-02-13 09:49
+1 Have the same problem.

**Comment by artem7902** [comment] 2018-02-13 14:37
Segwit branch does not work for me.

**Comment by schildbach** [comment] 2018-04-06 22:55
Fixed by https://github.com/bitcoinj/bitcoinj/pull/1552

**Closed by schildbach** 2018-04-06 22:55 UTC
