### ISSUE TITLE
Bech32 & segwit address support?

### ISSUE THREAD

**Issue by afk11** [bitcoinj/bitcoinj#1444] opened 2017-08-31 09:15 UTC
I've been reviewing for common libraries that may not yet have segwit address support. I haven't seen anyone work on it yet, please add this soon!

https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki

**Comment by schildbach** [comment] 2017-08-31 10:42
Duplicate of #1441

**Closed by schildbach** 2017-08-31 10:42 UTC
