### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by mitr15fan15v** [bitcoinj/bitcoinj#3078] opened 2023-05-07 20:21 UTC
After last commit 7cb61b03993797c55eca6f87dbe21b6576b82a4b
I can't build project
Including wallettemplate because Gradle 8.0
Including integration-test because Gradle 8.0
Warning: Using com.google.protobuf:protobuf-gradle-plugin:0.8.18 because Gradle 8.0
Adding 'testOnJdk8' task, because Gradle 8.0

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':bitcoinj-core:processResources' (type 'ProcessResources').
  - Gradle detected a problem with the following location: '/home/Projects/clear/bitcoinj/core/src/main/resources'.
    
    Reason: Task ':bitcoinj-core:processResources' uses this output of task ':bitcoinj-core:generateProto' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':bitcoinj-core:generateProto' as an input of ':bitcoinj-core:processResources'.
      2. Declare an explicit dependency on ':bitcoinj-core:generateProto' from ':bitcoinj-core:processResources' using Task#dependsOn.
      3. Declare an explicit dependency on ':bitcoinj-core:generateProto' from ':bitcoinj-core:processResources' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/home/Projects/clear/bitcoinj/core/src/main/proto'.
    
    Reason: Task ':bitcoinj-core:processResources' uses this output of task ':bitcoinj-core:generateProto' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':bitcoinj-core:generateProto' as an input of ':bitcoinj-core:processResources'.
      2. Declare an explicit dependency on ':bitcoinj-core:generateProto' from ':bitcoinj-core:processResources' using Task#dependsOn.
      3. Declare an explicit dependency on ':bitcoinj-core:generateProto' from ':bitcoinj-core:processResources' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 67ms

How fix?

**Comment by msgilligan** [comment] 2023-05-08 00:29
This is a duplicate of Issue #2779

**Closed** 2023-05-08 00:32 UTC

**Comment by mitr15fan15v** [comment] 2023-05-08 02:23
Thank you. I temporarily downgraded Gradle.
