### ISSUE TITLE
BlockFileLoader not compatible to recent Bitcoin Core releases any more

### ISSUE THREAD

**Issue by ubamnow404** [bitcoinj/bitcoinj#1506] opened 2018-01-26 17:36 UTC
I wrote a program to work with block files from bitcoin-core. It works good with data directory from bitcoin-core 0.12.1, but fails badly when applied to data directory from bitcoin-core 0.15.1:

```
java.lang.NegativeArraySizeException
        at org.bitcoinj.core.Message.readBytes(Message.java:334)
        at org.bitcoinj.core.TransactionInput.parse(TransactionInput.java:138)
        at org.bitcoinj.core.Message.<init>(Message.java:96)
        at org.bitcoinj.core.Message.<init>(Message.java:128)
        at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:57)
        at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:128)
        at org.bitcoinj.core.Transaction.parse(Transaction.java:564)
        at org.bitcoinj.core.Message.<init>(Message.java:96)
        at org.bitcoinj.core.Message.<init>(Message.java:128)
        at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:57)
        at org.bitcoinj.core.Transaction.<init>(Transaction.java:232)
        at org.bitcoinj.core.Block.parseTransactions(Block.java:242)
        at org.bitcoinj.core.Block.parse(Block.java:266)
        at org.bitcoinj.core.Message.<init>(Message.java:96)
        at org.bitcoinj.core.Message.<init>(Message.java:128)
        at org.bitcoinj.core.Block.<init>(Block.java:162)
        at org.bitcoinj.core.BitcoinSerializer.makeBlock(BitcoinSerializer.java:270)
        at org.bitcoinj.core.MessageSerializer.makeBlock(MessageSerializer.java:72)
        at org.bitcoinj.utils.BlockFileLoader.loadNextBlock(BlockFileLoader.java:154)
        at org.bitcoinj.utils.BlockFileLoader.hasNext(BlockFileLoader.java:87)
```

is this because of segwit?

**Comment by stachrom** [comment] 2018-02-02 22:25
No

**Comment by ubamnow404** [comment] 2018-02-03 21:51
@stachrom thank you but I am not touching the chainstate database at all. Only *.blk files using parser in bitcoinj

**Comment by stachrom** [comment] 2018-02-20 22:03
hmmm...

**Comment by milansismanovic** [comment] 2018-02-21 08:15
Looks like the segwit issue: https://github.com/bitcoinj/bitcoinj/issues/1348. See my attached JUnit code that shows that the failing deserialization is on the segwit transactions. Theere is the segwit branch here that should be able to deserialize, but is not merged with the main code here: https://github.com/bitcoinj/bitcoinj/pull/1441

Suggest to close the issue as a duplicate of the above issue1348.

**Comment by ubamnow404** [comment] 2018-02-21 14:29
Looking again, that this is of relation to segwit does not make any sense.

My program is recognize segwit txs when loaded from 0.12.1 blockchain using bitcoinj.

Confusing to me is that no one else report this problem, I mean how can you run a wallet if you can't (when needed) verify indexes with actual blockchain files?

**Comment by schildbach** [comment] 2018-02-21 16:05
You don't need Bitcoin Core's blockchain files to run a wallet with bitcoinj. Likely the the code was never adapted to Core's file format changes.

**Comment by ubamnow404** [comment] 2018-02-22 13:04
Okay, thank you for clarity. Everything's fine working with 0.12.1 *.blk files, so I will stick with that for a while and watch for when the new blockchain format support is available. Thank you for your work!

**Comment by schildbach** [comment] 2018-02-22 23:00
I suspect currently nobody is working on it. Maybe you'd want to try adapt the code yourself and contribute it back?

**Comment by ubamnow404** [comment] 2018-03-08 14:51
I absolutely would, but have no knowledge of the blockfile format at all. I use bitcoinj most to avoid that topic. 😉  Do you see any reason why depending on my 0.12.1 node for maintaining my block file set would be a bad idea?

**Comment by schildbach** [comment] 2018-04-06 22:54
Fixed by https://github.com/bitcoinj/bitcoinj/pull/1552

**Closed by schildbach** 2018-04-06 22:54 UTC
